---
- name: Install & Setup RabbitMQ with user
  hosts: rmqsrvgrp
  gather_facts: yes
  become: true
  tasks:
    - name: Install required dependencies
      apt:
        name:
          - curl
          - gnupg
          - apt-transport-https
          - lsb-release
        state: present
        update_cache: yes

    - name: Install Erlang (from default Ubuntu repo)
      apt:
        name: erlang
        state: present

    - name: Install compatible RabbitMQ version (3.9.27)
      apt:
        name: rabbitmq-server=3.9.27-0ubuntu0.2
        state: present
        update_cache: yes

    - name: Ensure RabbitMQ service is running and enabled
      service:
        name: rabbitmq-server=3.9.27-0ubuntu0.2
        state: started
        enabled: yes

    - name: Configure RabbitMQ to allow external connections
      copy:
        content: |
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config
      notify: Restart RabbitMQ

    - name: Enable RabbitMQ management plugin
      command: rabbitmq-plugins enable rabbitmq_management
      args:
        creates: /etc/rabbitmq/enabled_plugins
      notify: Restart RabbitMQ

    - name: Create RabbitMQ user with admin rights
      community.rabbitmq.rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify: Restart RabbitMQ

  handlers:
    - name: Restart RabbitMQ
      service:
        name: rabbitmq-server
        state: restarted
