---
- name: Map private IPs to hostnames in /etc/hosts
  hosts: all
  become: true
  tasks:
    - name: Import VPC setup variable
      include_vars: group_vars/hostsip

    - name:
      blockinfile:
        path: /etc/hosts
        block: |
          {{ web01_ip }} web01
          {{ app01_ip }} app01
          {{ rmq01_ip }} rmq01
          {{ mc01_ip }} mc01
          {{ db01_ip }} db01
